#!/bin/sh
cd "$(dirname "$0")/../../"
CONTENTSFOLD="$PWD"
####################################################
# this script will run when Kegworks is starting up
# before the X server or Wine starts
# $CONTENTSFOLD is the full path to the current
#       contents folder in the wrapper.
####################################################

# ENTER COMMANDS HERE
