#!/bin/sh
###################################################
#  CustomEXE code for Kegworks wrappers
#  Originally made by doh123@doh123.com
#
#  Version 6.0
#
#  This code is Open Source and licensed under the
#  terms of the GNU Lesser General Public License.
#  If the License file is not with this script, the
#  full license can be read at the following URL
#
#  http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
#
####################################################
# Set all variables
CMACOSFOLD="$(dirname "$0")"
MACOSFOLD="$CMACOSFOLD/../../../MacOS"
cd "$MACOSFOLD"
MACOSFOLD="$(echo "$PWD")"
CEXENAME="$(basename "${CMACOSFOLD%/Contents/MacOS}")"

# Launch wrapper
"$MACOSFOLD/WineskinLauncher" "CustomEXE" "$CEXENAME"
